<a class="btn success" href="/user/create">Naujas Vartotojas</a><br/><br/>
<table class="bordered-table zebra-striped">
    <thead>
        <th>Vardas</th>
        <th>Pavardė</th>
        <th>Veiksmai</th>
    </thead>
    <tbody>
        <tr>
            <?php 
            foreach($this->data as $user) {
                echo $this->partial('partials/user.phtml', $user);
            }
            ?>
        </tr>
    </tbody>
</table>